#data
dataset: delft_radar_lidar
# path: /data/public_dataset/delft/view_of_delft_PUBLIC
path: /DISK_F/view_of_delft_PUBLIC
category_name: Car # [Car, Van, Pedestrian, Cyclist, All]
bb_scale: 1.25
bb_offset: 2
lidar_point_sample_size: 1024 #lidar多采一些
radar_point_sample_size: 512 #radar相对少采一些
degrees: False
coordinate_mode: velodyne
up_axis: [ 0,0,1 ]
preload_offset: 10
data_limit_box: True
train_split: tiny_train
val_split: tiny_test
test_split: tiny_test
train_type: train_motion_cross_modal
num_candidates: 4
motion_threshold: 0.15
use_augmentation_radar_lidar: True #针对radar lidar的增强
limit_num_points_in_prev_box: 1 #motion_prosessing函数里面的对前一帧box里面的点的数量限制，少于这个数量则放弃该帧，会去取其他帧
limit_num_this_frame_subwindow_pc: 1 #motion_prosessing函数里面的对这一帧subwindow的点的数量限制，少于这个数量则放弃该帧，会去取其他帧


#model configuration
net_model: m2trackradarlidar #同时处理radar与lidar
box_aware: True
#---------cross attention------------------
num_queries: 1 #仅需预测一个box偏移
hidden_dim: 256
#---------image end------------------

#loss configuration
center_weight: 2
angle_weight: 10.0
seg_weight: 0.1
bc_weight: 1

motion_cls_seg_weight: 0.1

# testing config
use_z: True
limit_box: False
IoU_space: 3

#training
batch_size: 100
workers: 16
epoch: 180
from_epoch: 0
lr: 0.001
optimizer: Adam
lr_decay_step: 20
lr_decay_rate: 0.1
wd: 0
gradient_clip_val: 0.0